src/PassionCardAdmin/Controllers/ExportController.cs
using Microsoft.Reporting.WebForms;
using PassionCardAdmin.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PassionCardAdmin.Models;
using System.Text;
using System.Text.RegularExpressions;
using System.Configuration;
using System.IO;
using PassionCardAdmin.Services;
using PassionCardAdmin.Utilities;
using System.Web.Routing;

namespace PassionCardAdmin.Controllers
{
    public class ExportController : Controller
    {
        protected CardMasterService cardMasterService;
        protected Notify notify { get; set; }

        public ExportController()
        {
            cardMasterService = new CardMasterService();
        }

        // GET: Export
        public ActionResult Index()
        {
            ExportModelList model = new ExportModelList();
            model.MainExportModel = ConvertToModel(cardMasterService.GetExcelExportList());
            return View(model);
        }

        [HttpPost]
        public ActionResult ExportExcel(ExportModelList model)
        {
            try
            {
                var cardMasterService = new PassionCardAdmin.Services.CardMasterService();
                var dataList = cardMasterService.GetExcelExportList(model);
                var list = new List<ExportToXlsModel>();
                var groupedData = (from record in dataList
                                   group record by record.PrintBUStr into data
                                   orderby data.Key
                                   select new
                                   {
                                       GroupKey = data.Key,
                                       GroupValuesList = data.ToList()
                                   });
                //dataList.Clear();
                foreach (var group in groupedData)
                {
                    if (group.GroupValuesList.Count() > 0)
                    {
                        foreach (var item in group.GroupValuesList)
                        {
                            list.Add(item);
                        }

                    }
                }

                if (list != null && list.Count > 0)
                {
                    LocalReport localReport = new LocalReport();

                    localReport.ReportPath = Server.MapPath(Utilities.ConstantVar.ReportPath + "PA-Baby.rdlc");

                    ReportDataSource reportDataSource = new ReportDataSource("DataSet1", list);
                    localReport.DataSources.Clear();
                    localReport.DataSources.Add(reportDataSource);

                    localReport.Refresh();

                    string extensionString = "xls";
                    string outputType = "Excel";

                    string opFileName = "printing_list_PA_Baby_" + DateTime.Now.ToString("yyyyMMdd");

                    int recordID = cardMasterService.SavePrintFileDetails(opFileName, list);
                    if (recordID > 0)
                    {
                        ExportReportHelper.ReportWithImagesZip(localReport, outputType, opFileName, true, extensionString, Response, list, recordID);
                        ExportModelList returnModel = new ExportModelList();
                        returnModel.MainExportModel = ConvertToModel(cardMasterService.GetExcelExportList());
                        //return View(returnModel);
                        return RedirectToAction("Index");
                    }
                    else
                        notify = new Notify(NotifyLevel.Error, "Unable to update records.");
                }
                else
                {
                    notify = new Notify(NotifyLevel.Warning, "No records available for printing.");
                }
            }
            catch (Exception ex)
            {
                notify = new Notify(NotifyLevel.Error, ex.Message);
                ExceptionHelper.ExceptionTrack(ex);
            }
            return RedirectToAction("Index");
        }



        public ActionResult ACK()
        {
            ExportModelList model = new ExportModelList();
            model.MainExportModel = ConvertToModel(cardMasterService.GetAckExportList());
            return View(model);
        }

        [HttpPost]
        public ActionResult Ack(DateTime? ackDate, ExportModelList model)
        {
            try
            {
                if (ackDate == null)
                {
                    notify = new Notify(NotifyLevel.Error, "Please select date.");
                    model.MainExportModel.ForEach(x => x.IsChecked = true);
                    return View(model);
                }

                var cardMasterService = new PassionCardAdmin.Services.CardMasterService();
                var list = cardMasterService.GetAckExportList(model);

                if (list != null && list.Count > 0)
                {
                    List<string> lineList = new List<string>();
                    lineList.Add("BBCARDACK" + ackDate.Value.ToString("yyyyMMdd"));
                    foreach (var crdRecord in list)
                    {
                        lineList.Add(crdRecord.PAssionCardNumberStr + crdRecord.CanNumberStr + crdRecord.ExpiryDtYYMM + crdRecord.ActionFlags + GetReturnCode("0") + GetReturnMessage("") + GetOldezLinkNumber(crdRecord.OldPassionezLinkNumber));
                    }
                    lineList.Add("99999999" + list.Count.ToString("00000000"));
                    var fileName = "BBCARD_ACK_" + ackDate.Value.ToString("yyMMdd") + ".txt";

                    StringBuilder str = new StringBuilder();
                    const char LF = '\n';
                    for (int i = 0; i < lineList.Count; i++)
                    {
                        if (i == 0)
                        {
                            str.Append(lineList[i] + LF);
                        }
                        else if (i == (lineList.Count - 1))
                        {
                            str.Append(lineList[(lineList.Count - 1)] + LF);
                        }
                        else
                        {
                            str.Append(lineList[i] + LF);
                        }
                    }

                    var recordId = cardMasterService.SaveAckFileSendDetails(fileName, list);
                    string localfilename = string.Empty;

                    #region SaveToServerPath
                    if (recordId > 0)
                    {
                        var localpath = ConfigurationManager.AppSettings["ServerPathToSaveFiles"].ToString();
                        if (!Directory.Exists(localpath)) Directory.CreateDirectory(localpath);
                        localfilename = Path.Combine(localpath, recordId + ".txt");
                        using (var streamWrite = new StreamWriter(localfilename, true))
                        {
                            streamWrite.Write(str.ToString());
                            streamWrite.Close();
                        }
                    }
                    #endregion

                    return File(localfilename, "multipart/form-data", fileName);
                }
                else
                {
                    notify = new Notify(NotifyLevel.Warning, "No records available for printing.");
                    model.MainExportModel.ForEach(x => x.IsChecked = true);
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                notify = new Notify(NotifyLevel.Error, ex.Message);
                ExceptionHelper.ExceptionTrack(ex);
            }
            return View();
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (ConstantVar.IsPasswordExpired)
            {
                filterContext.Result = new RedirectToRouteResult(new RouteValueDictionary(new
                {
                    controller = "Account",
                    action = "ChangePassword"
                }));
            }
            base.OnActionExecuting(filterContext);
        }

        protected override void OnActionExecuted(ActionExecutedContext filterContext)
        {
            if (notify != null)
                TempData["notify"] = notify;

            base.OnActionExecuted(filterContext);
        }

        #region "Helper methods"

        /// <summary>
        /// Convert model from one to another
        /// </summary>
        /// <param name="list"></param>
        /// <returns></returns>
        private List<ExportModel> ConvertToModel(List<ExportToXlsModel> list)
        {
            return list.Select(x => new ExportModel()
            {
                RecordID = x.RecordId,
                Gender = x.Gender == "001" ? "Female" : "Male",
                IDNumber = x.IDNumber,
                IsChecked = true,
                NameOnCard = x.NameOnCard,
                PAssionCardNumber = x.PAssionCardNumber,
                SrNum = x.SrNo
            }).ToList();
        }


        /// <summary>
        /// retun 10 char string
        /// </summary>
        /// <param name="codeStr"></param>
        /// <returns></returns>
        private string GetReturnCode(string codeStr)
        {
            if (string.IsNullOrEmpty(codeStr))
                codeStr = string.Empty;
            if (codeStr.Length < 10)
                return codeStr.PadRight(10 - codeStr.Length);
            else
                return codeStr;
        }

        /// <summary>
        /// retun 100 char string
        /// </summary>
        /// <param name="messageStr"></param>
        /// <returns></returns>
        private string GetReturnMessage(string messageStr)
        {
            if (string.IsNullOrEmpty(messageStr))
                messageStr = string.Empty;
            if (messageStr.Length < 101)
                return messageStr.PadRight(101 - messageStr.Length);

src/PassionCardAdmin/Views/Export/ACK.cshtml
@model PassionCardAdmin.Models.ExportModelList
@{
    ViewBag.Title = "Export Acknowledgement";
}

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-success">

                <div class="box-header with-border">
                    <div class="row">
                        <div class="col-md-3">
                            <h3 class="box-title"><b> Export Acknowledgement</b></h3>
                        </div>
                    </div>
                </div>

                @using (@Html.BeginForm("ACK", "Export", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="box-body">

                        <div class="row">
                            <div class="col-md-2">
                                &nbsp;
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group text-right">
                                    <label>Date</label>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <input type="text" id="ackDate" name="ackDate" class="form-control" />
                                </div>
                            </div>

                            <div class="col-md-2 col-md-offset-4 pull-right">
                                <div class="form-group" id="SubmitDiv">
                                    <input type="submit" value="Export" class="btn btn-block btn-primary" id="Submit" />
                                </div>
                                <div class="form-group hidden" id="RefreshDiv">
                                    <a href="@Url.Content("~/Export/ACK")" class="btn btn-block btn-primary" id="Refresh">Refresh Data</a>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12 col-md-12">
                                <div class=" table-responsive">
                                    <table id="RecordReport-table" class="table table-bordered  table-striped tablesorter">
                                        <thead class="ors-table-header-- table-header">
                                            <tr>
                                                <th class="text-center"><input type="checkbox" style="zoom:1.3;" checked="checked" id="chkCheckUnCheckAll" /></th>
                                                <th class="text-center">Sr No</th>
                                                <th class="text-center">Record ID</th>
                                                <th class="text-center">ID Number</th>
                                                <th class="text-center">Name On Card</th>
                                                <th class="text-center">PAssion Card Number</th>
                                                @*<th class="text-center">Birthday</th>*@
                                                <th class="text-center">Gender</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @for (int index = 0; index < Model.MainExportModel.Count; index++)
                                            {
                                                <tr>
                                                    <td class="text-center">@Html.CheckBoxFor(x => x.MainExportModel[index].IsChecked, new { @class = "chkCheckbox" })</td>
                                                    <td class="text-center">@Model.MainExportModel[index].SrNum</td>
                                                    @Html.HiddenFor(x => x.MainExportModel[index].SrNum)
                                                    <td class="text-center">@Model.MainExportModel[index].RecordID</td>
                                                    @Html.HiddenFor(x => x.MainExportModel[index].RecordID)
                                                    <td class="text-center">@Model.MainExportModel[index].IDNumber</td>
                                                    @Html.HiddenFor(x => x.MainExportModel[index].IDNumber)
                                                    <td class="text-center">@Model.MainExportModel[index].NameOnCard</td>
                                                    @Html.HiddenFor(x => x.MainExportModel[index].NameOnCard)
                                                    <td class="text-center">@Model.MainExportModel[index].PAssionCardNumber</td>
                                                    @Html.HiddenFor(x => x.MainExportModel[index].PAssionCardNumber)
                                                    <td class="text-center">@Model.MainExportModel[index].Gender</td>
                                                    @Html.HiddenFor(x => x.MainExportModel[index].Gender)
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                    </div>
                }

            </div>
        </div>
    </div>
</section>

@Scripts.Render("~/bundles/commonDatejs")

<script>
    $(document).ready(function () {

        //Datepicker Binding
        $('#ackDate').datepicker({ format: "dd M yyyy", autoclose: true });

        //submit button on this button click
        $("#Submit").click(function (event) {
            if ($('.chkCheckbox:checked').size() == 0) {
                return false;
            }
            if ($('.chkCheckbox:checked').size() > 0) {
                $("#form").submit();
            }
            $("#RefreshDiv").removeClass("hidden");
            $("#SubmitDiv").addClass("hidden");
        });

        //Rfersh page on this button click
        //$("#Refresh").click(function (event) {
        //    $("#LoadingDiv").show();
        //    window.location.reload();
        //});


        //check all checkboxes on checkall button click.
        $('#chkCheckUnCheckAll').change(function () {
            if ($(this).is(":checked")) {
                $('.chkCheckbox').prop('checked', true);
            }
            else {
                $('.chkCheckbox').prop('checked', false);
            }
        });

        //Check box event for checkall on all checkboxes checked and viceversa.
        $('.chkCheckbox').change(function () {
            if ($('.chkCheckbox:checked').size() < $('.chkCheckbox').size()) {
                $('#chkCheckUnCheckAll').prop('checked', false);
            }
            else if ($('.chkCheckbox:checked').size() == $('.chkCheckbox').size()) {
                $('#chkCheckUnCheckAll').prop('checked', true);
            }
        });
    });
</script>

src/PassionCardAdmin/Views/Export/Index.cshtml
@model PassionCardAdmin.Models.ExportModelList
@{
    ViewBag.Title = "Export Excel";
}

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-success">

                <div class="box-header with-border">
                    <div class="row">
                        <div class="col-md-3">
                            <h3 class="box-title"><b> Export Excel</b></h3>
                        </div>
                    </div>
                </div>

                @using (@Html.BeginForm("ExportExcel", "Export", null, FormMethod.Post, new { enctype = "multipart/form-data", @id = "form" }))
                {
                    <div class="box-body">

                        <div class="row">
                            <div class="col-md-2">
                                &nbsp;
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-2 col-md-offset-4 pull-right">
                                <div class="form-group" id="SubmitDiv">
                                    <input type="button" value="Export Excel" class="btn btn-block btn-primary" id="Submit" />
                                </div>
                                <div class="form-group hidden" id="RefreshDiv">
                                    <a href="@Url.Content("~/Export/Index")" class="btn btn-block btn-primary" id="Refresh">Refresh Data</a>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12 col-md-12">
                                <div class=" table-responsive">
                                    <table id="RecordReport-table" class="table table-bordered  table-striped tablesorter">
                                        <thead class="ors-table-header-- table-header">
                                            <tr>
                                                <th class="text-center"><input type="checkbox" style="zoom:1.3;" checked="checked" id="chkCheckUnCheckAll" /></th>
                                                <th class="text-center">Sr No</th>
                                                <th class="text-center">Record ID</th>
                                                <th class="text-center">ID Number</th>
                                                <th class="text-center">Name On Card</th>
                                                <th class="text-center">PAssion Card Number</th>
                                                @*<th class="text-center">Birthday</th>*@
                                                <th class="text-center">Gender</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @for (int index = 0; index < Model.MainExportModel.Count; index++)
                                            {
                                                <tr>
                                                    <td class="text-center">@Html.CheckBoxFor(x => x.MainExportModel[index].IsChecked, new { @class = "chkCheckbox" })</td>
                                                    <td class="text-center">@Model.MainExportModel[index].SrNum</td>
                                                    @Html.HiddenFor(x => x.MainExportModel[index].SrNum)
                                                    <td class="text-center">@Model.MainExportModel[index].RecordID</td>
                                                    @Html.HiddenFor(x => x.MainExportModel[index].RecordID)
                                                    <td class="text-center">@Model.MainExportModel[index].IDNumber</td>
                                                    @Html.HiddenFor(x => x.MainExportModel[index].IDNumber)
                                                    <td class="text-center">@Model.MainExportModel[index].NameOnCard</td>
                                                    @Html.HiddenFor(x => x.MainExportModel[index].NameOnCard)
                                                    <td class="text-center">@Model.MainExportModel[index].PAssionCardNumber</td>
                                                    @Html.HiddenFor(x => x.MainExportModel[index].PAssionCardNumber)
                                                    <td class="text-center">@Model.MainExportModel[index].Gender</td>
                                                    @Html.HiddenFor(x => x.MainExportModel[index].Gender)
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                    </div>
                }

            </div>
        </div>
    </div>
</section>
<script>
    $(document).ready(function () {

        //submit button on this button click
        $("#Submit").click(function (event) {
            if ($('.chkCheckbox:checked').size() > 0) {
                $("#form").submit();
            }
            $("#RefreshDiv").removeClass("hidden");
            $("#SubmitDiv").addClass("hidden");
        });

        ////Rfersh page on this button click
        //$("#Refresh").click(function (event) {
        //    $("#LoadingDiv").show();
        //    window.location.reload();
        //});


        //check all checkboxes on checkall button click.
        $('#chkCheckUnCheckAll').change(function () {
            if ($(this).is(":checked")) {
                $('.chkCheckbox').prop('checked', true);
            }
            else {
                $('.chkCheckbox').prop('checked', false);
            }
        });

        //Check box event for checkall on all checkboxes checked and viceversa.
        $('.chkCheckbox').change(function () {
            if ($('.chkCheckbox:checked').size() < $('.chkCheckbox').size()) {
                $('#chkCheckUnCheckAll').prop('checked', false);
            }
            else if ($('.chkCheckbox:checked').size() == $('.chkCheckbox').size()) {
                $('#chkCheckUnCheckAll').prop('checked', true);
            }
        });
    });
</script>