src/PassionCardAdmin/Controllers/ReportController.cs
using PassionCardAdmin.Helpers;
using PassionCardAdmin.Models;
using PassionCardAdmin.Services;
using PassionCardAdmin.Utilities;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace PassionCardAdmin.Controllers
{
    public class ReportController : Controller
    {
        private FileService fileService;
        private RecordService recordService;
        private PhotoReportService photoReportService;
        protected Notify notify { get; set; }

        /// <summary>
        /// Constructor.
        /// </summary>
        public ReportController()
        {
            fileService = new FileService();
            recordService = new RecordService();
            photoReportService = new PhotoReportService();
        }

        // GET: Report
        [HttpGet]
        public ActionResult FileReport()
        {
            return View();
        }

        [HttpGet]
        public ActionResult RecordReport()
        {
            return View();
        }

        /// <summary>
        /// Summary Report View.
        /// </summary>
        /// <returns></returns>
        public ActionResult SummaryReport()
        {
            return View();
        }

        /// <summary>
        /// Print BU Report.
        /// </summary>
        /// <returns></returns>
        public ActionResult PrintBUReport()
        {
            return View();
        }

        /// <summary>
        /// Print BU Report.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult PrintBUReport(PrintBUReportModel model)
        {
            var data = recordService.GetPrintBUReport(model);
            if (data.Count > 0)
            {
                recordService.ExportPrintBUReport(data, model, false, Response, Server);
            }
            else
            {
                notify = new Notify(NotifyLevel.Warning, "No records available for export.");
            }
            return View(model);
        }

        //Download file on download link given in list.
        public ActionResult Download(int RecordId, int FileType, string FileName)
        {
            var localpath = ConfigurationManager.AppSettings["ServerPathToSaveFiles"].ToString();
            var extension = GetExtensionByType(FileType);
            FileName = GetFileNameByType(FileType, FileName);

            var localfilename = Path.Combine(localpath, RecordId + extension);

            if (System.IO.File.Exists(localfilename))
            {
                return File(localfilename, "multipart/form-data", FileName);
            }
            else
            {
                notify = new Notify(NotifyLevel.Error, "File does not exists.");
                return RedirectToAction("FileReport");
            }
        }

        public ActionResult EditRecord(int RecordId)
        {
            var record = fileService.GetRecord(RecordId);
            if (record != null)
            {
                if (record.RecordStatus == Enums.Enum.RecordStatus.PC.ToString())
                {
                    CardEditModel model = new CardEditModel()
                    {
                        RecordId = record.RecordID,
                        CardCANExpiryDt = record.CardCANExpiryDt,
                        CardCANNumber = record.CardCANNumber
                    };
                    return View(model);
                }
                else
                {
                    notify = new Notify(NotifyLevel.Error, "Record status must be PC or RD");
                    return RedirectToAction("RecordReport");
                }
            }
            else
            {
                notify = new Notify(NotifyLevel.Error, "Record not found.");
                return RedirectToAction("RecordReport");
            }
        }

        [HttpPost]
        public ActionResult EditRecord(CardEditModel model)
        {
            if (ModelState.IsValid)
            {
                var result = fileService.UpdateCardDetails(model);
                if (result)
                {
                    notify = new Notify(NotifyLevel.Success, "Card details are updated successfully.");
                    return RedirectToAction("RecordReport");
                }
                else
                {
                    ModelState.AddModelError("", "Something went wrong while updating record");
                }
            }
            return View(model);
        }

        /// <summary>
        /// This function Shows report for reset photo images
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult PhotoResetReport()
        {
            return View();
        }

        /// <summary>
        /// Post event for photo reset option.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult PhotoResetReport(PhotoResetReportModel model)
        {
            //if (ModelState.IsValid)
            //{
                var result = photoReportService.ExportToReport(model, false, Response, Server);
                if (result)
                {

                }
            //}
            return View(model);
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (ConstantVar.IsPasswordExpired)
            {
                filterContext.Result = new RedirectToRouteResult(new RouteValueDictionary(new
                {
                    controller = "Account",
                    action = "ChangePassword"
                }));
            }
            base.OnActionExecuting(filterContext);
        }

        protected override void OnActionExecuted(ActionExecutedContext filterContext)
        {
            if (notify != null)
                TempData["notify"] = notify;

            base.OnActionExecuted(filterContext);
        }

        #region Helper Methods

        private string GetExtensionByType(int fileType)
        {
            if (fileType == (int)Enums.Enum.FileTypes.ExcelExport)
                return ".zip";
            else
                return ".txt";
        }

        private string GetFileNameByType(int fileType, string FileName)
        {
            if (fileType == (int)Enums.Enum.FileTypes.ExcelExport)
                return FileName + ".zip";
            else
                return FileName;
        }

        /// <summary>
        /// Get File list as per filter applied on view.
        /// </summary>
        /// <param name="form"></param>
        /// <returns></returns>
        public JsonResult GetFileReport(FormCollection form)
        {
            return Json(fileService.GetFileList(form), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Get card details list as per filter applied on view.
        /// </summary>
        /// <param name="form"></param>
        /// <returns></returns>
        public JsonResult GetCardMasterDetailsReport(FormCollection form)
        {
            return Json(recordService.GetRecordList(form), JsonRequestBehavior.AllowGet);
        }


        /// <summary>
        /// Get data by type(monthly/weekly)
        /// </summary>
        /// <param name="form"></param>
        /// <returns></returns>
        public JsonResult GetDataByType(FormCollection form)
        {
            return Json(recordService.GetDataByType(form), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Get data of printBU Report
        /// </summary>
        /// <param name="form"></param>
        /// <returns></returns>
        public JsonResult GetPrintBUReport(FormCollection form)
        {
            return Json(recordService.GetPrintBUReport(form), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Get all data from Image gistory table.
        /// </summary>
        /// <param name="form"></param>
        /// <returns></returns>
        public JsonResult GetImageReport(FormCollection form)
        {
            return Json(photoReportService.GetPhotoReport(form), JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}

src/PassionCardAdmin/Views/Report/EditRecord.cshtml
@model PassionCardAdmin.Models.CardEditModel
@{
    ViewBag.Title = "Edit Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-success">

                <div class="box-header with-border">
                    <div class="row">
                        <div class="col-md-3">
                            <h3 class="box-title"><b> Edit Record</b></h3>
                        </div>

                    </div>
                </div>

                @using (Html.BeginForm("EditRecord", "Report", FormMethod.Post))
                {
                    @Html.HiddenFor(x => x.RecordId)
                    <div class="box-body">
                        <div class="row">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-xs-3">
                                    </div>
                                    <div class="col-xs-6">
                                        <span class="validationheader text-left">
                                            <b>
                                                @Html.ValidationSummary(true, "! Record changes unsuccessful. Please correct the errors and try again.", new { @class = "alert alert-error-Ni col-lg-10 col-lg-offset-1 my-padding-10" })
                                            </b>
                                        </span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4 text-right">
                                        <div class="form-group">
                                            <label>
                                                Card CAN Number
                                            </label>
                                        </div>
                                    </div>

                                    <div class="col-md-4">
                                        <div class="form-group">
                                            @Html.TextBoxFor(model => model.CardCANNumber, htmlAttributes: new { @class = "form-control col-md-3", @id = "txtCardCANNumber", autocomplete = "off", maxlength = "16", onpaste = "return false" })
                                            @Html.ValidationMessageFor(model => model.CardCANNumber, "", new { @class = "text-danger" })

                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4 text-right">
                                        <div class="form-group">
                                            <label>
                                                Card CAN Expiry Date
                                            </label>
                                        </div>
                                    </div>

                                    <div class="col-md-4">
                                        <div class="form-group">
                                            @Html.TextBoxFor(model => model.CardCANExpiryDt, htmlAttributes: new { @class = "form-control col-md-3", @id = "txtCardCANExpiryDt", autocomplete = "off", maxlength = "4", onpaste = "return false" })
                                            @Html.ValidationMessageFor(model => model.CardCANExpiryDt, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4 text-right">
                                    </div>
                                    <div class="col-md-2">
                                        <input type="submit" value="Update" class="btn btn-block btn-primary" id="BtnSave" />
                                    </div>
                                    <div class="col-md-2">
                                        <a value="Update" class="btn btn-block btn-warning" href="@Url.Content("~/Report/RecordReport")">Cancel</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

src/PassionCardAdmin/Views/Report/FileReport.cshtml
@*@model PassionCardAdmin.Models.FileListPagingModel*@
@{
    ViewBag.Title = "File Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-success">

                <div class="box-header with-border">
                    <div class="row">
                        <div class="col-md-3">
                            <h3 class="box-title"><b> File Report</b></h3>

                        </div>
                    </div>
                </div>

                @*@using (@Html.BeginForm("Transaction", "Report", FormMethod.Post))
                    {*@
                <input type="hidden" id="txtSortColumnServer" />
                <input type="hidden" id="txtSortOrderServer" />
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="col-lg-6">
                                <div class="col-md-4 pull-left">
                                    <div class="form-group">
                                        <input id="txtFileName" type="text" class="form-control  " placeholder="File Name">
                                    </div>
                                </div>
                                <div class="col-md-4 pull-left">
                                    <div class="form-group">
                                        <a id="btnSearch" class="btn btn-block btn-primary pull-right">Filter</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12 col-md-12">
                            <div class=" table-responsive">
                                <table id="File-table" class="table table-bordered  table-striped tablesorter">
                                    <thead class="table-header">
                                        <tr>
                                            <th class="text-center header Sortactive">Record Id</th>
                                            <th class="text-center header">File Name</th>
                                            <th class="text-center header">Records</th>
                                            <th class="text-center header">Header file Id</th>
                                            <th class="text-center header">Footer file Id</th>
                                            <th class="text-center header" style="width:250px;">Record creation Date</th>
                                            <th class="text-center header">File Type</th>
                                            <td class="text-center"><strong>Download</strong></td>
                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- /.box-body -->
                <div class="box-footer">
                    <div class="row">
                        <div class="col-sm-2 col-md-2">
                        </div>
                        <div class="col-sm-8 col-md-8 text-center">
                            <!--<div class="dataTables_paginate paging_simple_numbers" id="Staff_paginate">
                                <ul class="pagination">
                                    <li class="paginate_button disabled MouseHourHand" id="Staff_previous">
                                        <a class="previous" aria-controls="example1" data-dt-idx="0" tabindex="0">Previous</a>
                                    </li>
                                    <li class="paginate_button txtbox">
                                        <a aria-controls="example1" data-dt-idx="1" tabindex="0">
                                            page
                                            <span id="currentPage" type="text" style="width: 30px;">@*Model.page*@1</span>
                                            of <span id="spnTotalPages">@*Model.total*@1 </span>
                                        </a>

                                    </li>
                                    <li class="paginate_button MouseHourHand" id="Staff_next"><a class="Next" aria-controls="example1" data-dt-idx="7" tabindex="0">Next</a></li>
                                </ul>
                            </div>-->
                            <div id="page-selection"></div>
                        </div>
                    </div>
                </div>
                @*}*@
            </div>
        </div>
    </div>
</section>

@Scripts.Render("~/bundles/paginationjs")
<script>

    RefreshClass(true);

    //Filter button click event.
    $('#btnSearch').click(function (e) {
        GetData(1, $('#page-selection'), false);
    });

    //Header clas click
    $(".header").on("click", function () {
        $(".header").parent().find(".Sortactive").removeClass("Sortactive");
        $(this).addClass("Sortactive");
        RefreshClass(false);

    });

    //refresh active class on every click.
    function RefreshClass(flag) {
        $(".header").each(function () {
            if ($(this).hasClass("Sortactive")) {
                if ($(this).hasClass("headerSortUp")) {
                    $(this).removeClass("headerSortUp");
                    $(this).addClass("headerSortDown");
                }
                else {
                    $(this).addClass("headerSortUp");
                    $(this).removeClass("headerSortDown");
                }
            }
            else {
                $(this).removeClass("headerSortUp");
                $(this).removeClass("headerSortDown");
            }
        });
        if (flag) {
            GetData(1, $('#page-selection'), true);
        }
        else {
            GetData(1, $('#page-selection'), false);
        }
    };

    //Gets Data from Database using AJAX
    function GetData(page, bootPag, flag) {
        $('#LoadingDiv').show();

        var data = {
            PageSize: 10,
            PageIndex: page,
            IsSearch: false
        };

        var fileName = $('#txtFileName').val();
        var UpDown = "";
        if ($('.Sortactive').hasClass('headerSortUp'))
            UpDown = 'ASC';
        else if ($('.Sortactive').hasClass('headerSortDown'))
            UpDown = 'DESC';
        var sortColumn = $('.Sortactive').text();
        $('#txtSortColumnServer').val(sortColumn);
        $('#txtSortOrderServer').val(UpDown);

        $.ajax({
            type: "POST",
            url: '@Url.Content("~/Report/GetFileReport")',
            data: { page: page, rows: 10, SortColumn: sortColumn, SortOrder: UpDown, FileName: fileName },
            success: function (data) {
                if (flag) {
                    InitializePagination(data.total, data.page);
                }
                else {
                    if (data.total == 0 && data.page == 0) {
                        $('#page-selection ul').html("");
                    }
                    else
                        bootPag.bootpag({
                            total: data.total,
                            page: data.page,
                            maxVisible: 10,
                            leaps: true,
                            firstLastUse: true,
                            first: '←',
                            last: '→',
                            wrapClass: 'pagination',
                            activeClass: 'active',
                            disabledClass: 'disabled',
                            nextClass: 'next',
                            prevClass: 'prev',
                            lastClass: 'last',
                            firstClass: 'first'
                        });
                }

                var tableBody = "";
                if (data) {

                    var row = "";
                    var sum = 0;

                    if (data.data.length == 0) {
                        row = '<tr>' +
                             '<td colspan="21" style="text-align: center" class="nodata">' + 'No data available in table' + '</td>' +
                         '</tr>';

                        tableBody = tableBody + (row);
                    }
                    else {
                        for (var i = 0; i < data.data.length; i++) {
                            var file = data.data[i];
                            row +=
                                '<tr>' +
                                    '<td style="text-align: center">' + file.RecordID + '</td>' +
                                    '<td style="text-align: center">' + file.FileName + '</td>' +
                                    '<td style="text-align: center">' + file.FooterRecordTotals + '</td>' +
                                    '<td style="text-align: center">' + file.HeaderFileID + '</td>' +
                                    '<td style="text-align: center">' + file.FooterFileID + '</td>' +
                                    '<td style="text-align: center">' + file.RecordCreatedDateStr + '</td>' +
                                    '<td style="text-align: center">' + file.FileTypreStr + '</td>' +
                                    '<td style="text-align: center">' + '<a href="@Url.Content("~/Report/Download/?RecordId=")' + file.RecordID + "&FileType=" + file.FileType + "&FileName=" + file.FileName + '" class="view file"><span class="fa fa-download fa-fw" title="Download"></span></a>' + '</td>';
                            //'<td style="text-align: center">' + "Download" + '</td>';
                        }
                        //'<td style="text-align: center">' + '<a href="#" class="view file"><span class="fa fa-file fa-fw" title="Edit"></span></a>' + '</td>'
                        //'<td style="text-align: center">' + '<a target="_blank" href="#' + transaction.TransactionDateString + '" class="view"><span class="fa fa-file fa-fw" title="Edit"></span></a>' + '</td>'


                        tableBody = tableBody + (row);
                        row = "";
                    }
                    $('#File-table tbody').html(tableBody);
                }
                $('#LoadingDiv').hide();
            },
            error: function (e) {
                console.log(e);
                //alert(e);
                $('#LoadingDiv').hide();
            }
        });
    }
</script>
<script>
    function InitializePagination(totalPages, CurrentPage) {
        // init bootpag
        $('#page-selection').bootpag({
            total: totalPages,
            page: CurrentPage,
            maxVisible: 10,
            leaps: true,
            firstLastUse: true,
            first: '←',
            last: '→',
            wrapClass: 'pagination',
            activeClass: 'active',
            disabledClass: 'disabled',
            nextClass: 'next',
            prevClass: 'prev',
            lastClass: 'last',
            firstClass: 'first'
        }).on("page", function (event, num) {
            GetData(num, $(this), false);
        });
    }
</script>